version: "3"
services:
  redis:
    image: redis:alpine
    container_name: squash-api-redis
    command:
      - redis-server
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    container_name: squash-api-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: squash
      MYSQL_DATABASE: squash_local

  influxdb:
    image: influxdb:1.8.3
    container_name: squash-api-influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  # Run chronograf on a different port to avoid
  # collision with Jupyter server.
  chronograf:
    image: chronograf:1.8.8
    container_name: squash-api-chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "8087:8888"
    links:
      - influxdb
